signs:
  - id: sign-win-linux
    signature: "${artifact}.sig"
    ids: 
    - git-ssh-sign
    artifacts: binary
    args: ["--batch", "-u", "{{ .Env.GPG_FINGERPRINT }}", "--output", "${signature}", "--detach-sign", "${artifact}"]

  - id: sign-macos
    signature: "${artifact}.dmg"
    ids: 
    - git-ssh-sign-macos
    cmd: gon
    args:
    - gon.hcl
    artifacts: all

builds:
  - binary: git-ssh-sign
    id: git-ssh-sign
    main: ./cmd/ssh-sign/main.go
    goos:
    - linux
    - windows
    goarch:
    - amd64
    - arm64
    env:
      - CGO_ENABLED=0

  # Separated build for the MacOS binary for notarization
  - binary: git-ssh-sign
    id: git-ssh-sign-macos
    main: ./cmd/ssh-sign/main.go
    goos:
    - darwin
    goarch:
    - amd64
    - arm64
    env:
      - CGO_ENABLED=0
