builds:
  - binary: git-ssh-sign
    id: git-ssh-sign
    main: ./cmd/ssh-sign/main.go
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

  # Separated build for the MacOS binary for notarization
  - binary: git-ssh-sign
    id: git-ssh-sign-macos
    main: ./cmd/ssh-sign/main.go
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    hooks:
      post: gon gon.hcl

archives:
  - builds:
      - git-ssh-sign
      - git-ssh-sign-macos
    format: binary
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

signs:
  - id: sign-win-linux
    ids:
      - git-ssh-sign
    artifacts: binary
    args:
      [
        "--batch",
        "-u",
        "{{ .Env.GPG_FINGERPRINT }}",
        "--output",
        "${signature}",
        "--detach-sign",
        "${artifact}",
      ]
    output: true # for debugging
